#+TITLE: Second Era

** =0 2E= Great cataclism, end of the civil war, end of the Empire

** =99 2E= Foundation of the [[./na-aavin_country.org][Kingdom of Na'aavin]]

On the ruins of the old world destroyed by the great civil war of the Empire, settlements in the north of the continent began to gather and unify under the banner, of Liten I of Si'eten. They will later be known as the realm of the north, or Na'aavin

** =103 2E= Rise of the Great Barrier

Nations on the western end of the continent, fearing that if the people of the east united again under a single banner they could bring them down as violently as the great cataclism, magically rose a whole mountain chain with peaks a dozen of kilometers above sea level.

Obviously, it was not the work of a day, but rather the work of sevral generations working to a single goal, separate the continent in half to keep the destruction to the east of the barrier.

No one knows what happened next to those who rose the barrier as all comunications where cut for centuries

** =133 2E= Foundation of the [[./esiikiva_country.org][Union of the merchant cities of Esiikiva]]

In order to resist the influence of the ever growing [[./na-aavin_country.org][Kingdom of Na'aavin]], some trade focussed, guild run cities in the southeast of the continent gathered as a confederation under the impulse of Ketii Atelo'ee, Guild master of Atjekila's (Nowdays' Tjeelat) Carpenter's guild and governor of the city.

At this point in time, the member cities are Sa'ekiila (Njelat), Osheiin and Atjekila (Tjeelat)

It was then decided that the Union will be run by a council formed of the governors of each city, as well as that member cities will continue using their existing government form, and ways to nominate said government, to manage internal affairs.

** =169 2E= -- =172 2E= First Western Na'aavan war

Greedy of expension, the [[./na-aavin_country.org][Kingdom of Na'aavin]] planned a massive invasion of the western realms that didnt join the kingdom willingly. However due to bad organization, the attack didnt go as planned and the Na'aavan army was sent home with heavy casualities.

** [[./tjaakesiva_city.org][Tjaakesiva]] and [[./talekoon_city.org][Talekoon]] join the [[./esiikiva_country.org][Union of Esiikiva]]

[[./README.org][Back to the menu]]
