#+TITLE: Njelat

** Résumé

*Njelat* est la capitale de l'[[./esiikiva_country.org][Union des cités marchades d'Esiikiva]]. Située sur la côte est, c'est avec ses 200.000 âmes la seconde plus grande ville du continent, juste derrière [[./si-eten_city.org][Si'eten]], capitale du [[./na-aavan_country.org][Royaume de Na'aavan]] au nord du continent.

** Informations
| Population       | 200 000                                  |
| Pays             | Union des cités marchades d'Esiikiva     |
| Gouvernement     | Conseil des Guildes                      |
| Statut           | Capitale                                 |

** Population

Etant la capitale d'une nation de commerce, Njelat est un bouillonnement culturel: on y trouve principalement des Esiikivan, mais aussi des Na'aavans, des insulaires du Nord-Est et des nomades Tjeehevan.

** Politique

La ville est gouverné par le Conseil des Guildes, une organisation comprenant les guildes majeures présentes sur place. Cependant, étant donné que c'est aussi la capitale de l'[[./esiikiva_country.org][Union des cités marchades d'Esiikiva]], le gouvernement de l'Union prend aussi part au décisions.

** Economie

L'économie de Njelat tourne autour du commerce grace a la guilde des marchants des mers et de la guilde des marins qui sont les plus influentes de la ville. Cela dit il y a tout de même a Njelat une long tradition des potteries et céramiques qui de leur haute qualité et popularité font parti des biens de luxes vendus dans le monde à des prix d'or.

N'étant pas une ville frontalière, Njelat est une ville dont le commerce est centré sur l'intérieur dans un pays centré beaucoup sur l'import-export. Délégant ce dernier à des villes plus avantageusement situées telles que [[./kasilee_city.org][Kasilee]].

** Histoire

Avant de remplacer [[./tjeelat_city.org][Tjeelat]] en temps que capitale de l'Union en /<insérer date>/, la ville était connue sous le nom de Sa'ekiila. On peut encore de nos jours voir l'ancien nom sur des batiments historiques de la ville tels que la mairie ou on peut lire =Sa'ekiilen Kaatanan Okatale= signifiant "Maison des guildes de Sa'ekiila".


[[./README.org][Retour au menu]]
