#+TITLE: Tjeelat

** Abstract

*Tjeelat* is the most southern and smallest member city of the [[./esiikiva_country.org][Union of the merchant cites of Esiikiva]]. However it is one of the most culturally important one, as it is the one around which the uninon consolidated, granting the status of former capital.

** Info block
| Population | 30 000                                   |
| Country    | Union of the merchant cities of Esiikiva |
| Goverment  | Assembly of the Guilds and the People    |
| Status     | Member city                              |

** Population

Since the city lost its capital status its population is less diverse than before. Nowdays, aside from the occasional adventurer you will almost exclusively find Esiikivans in its streets.

** Politics

While most cities of the union are managed solely by their council of guilds, Tjelat is run by an elected assembly in which each guild nominate two member to defend its interests for a total of 70 guild representants in addition to the 105 representants elected by the citizens.

Those 175 representants then elect the governor of the city. While the governor could in theory be any regular citizen of Tjeelat, it is custumarly the longest serving representant of the assembly who is nominated

** Economy

Being the most southern important city of the union and the whole continent, it benefits of a wetter climate than the rest. This allowed it to develop a important food production with the main products being rice and fruits. It also has an important jewelry and fine craftsmanship.

Almost none of the exports from Tjelat directly goes to their final destination, rather going through the trading hubs of [[./kasilee_city.org][Kasilee]], [[./njelat_city.org][Njelat]] and [[./tjaakesiva_city.org][Tjaakesiva]]

** History

Before the capital moved to [[./njelat_city.org][Njelat]] and both city got renamed Tjeelat was known as Atjekila. We can still find this named used in the formal name of the assembly which is =Atjekili Tjeelatan Kaatani Otenan Okalate= whose meaning is “House of the people and guilds of Atjekila-Tjeelat”.

[[./README.org][Back to the menu]]
